runtime: python311

service: rocaleda-fp-candidates-ms

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

env_variables:
    CANDIDATE_CREATION_SUBSCRIPTION_NAME: VAR_CANDIDATE_CREATION_SUBSCRIPTION_NAME
    DB_URL: VAR_DB_URL
    GOOGLE_CLOUD_PROJECT: VAR_PROJECT_ID

vpc_access_connector:
    name: projects/VAR_PROJECT_ID/locations/VAR_REGION/connectors/VAR_VPC_CONNECTOR
    egress_setting: all-traffic
