runtime: python311

service: rocaleda-fp-ms-template

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

env_variables:
    CANDIDATE_CREATION_SUBSCRIPTION_NAME: VAR_CANDIDATE_CREATION_SUBSCRIPTION_NAME
    DB_URL: VAR_DB_URL
    GOOGLE_CLOUD_PROJECT: VAR_GOOGLE_CLOUD_PROJECT
    GOOGLE_CLOUD_TYPE: VAR_GOOGLE_CLOUD_TYPE
    GOOGLE_CLOUD_PRIVATE_KEY_ID: VAR_GOOGLE_CLOUD_PRIVATE_KEY_ID
    GOOGLE_CLOUD_PRIVATE_KEY: |
        VAR_GOOGLE_CLOUD_PRIVATE_KEY
    GOOGLE_CLOUD_CLIENT_EMAIL: VAR_GOOGLE_CLOUD_CLIENT_EMAIL
    GOOGLE_CLOUD_CLIENT_ID: VAR_GOOGLE_CLOUD_CLIENT_ID
    GOOGLE_CLOUD_AUTH_URI: VAR_GOOGLE_CLOUD_AUTH_URI
    GOOGLE_CLOUD_TOKEN_URI: VAR_GOOGLE_CLOUD_TOKEN_URI
    GOOGLE_CLOUD_AUTH_PROVIDER_X509_CERT_URL: VAR_GOOGLE_CLOUD_AUTH_PROVIDER_X509_CERT_URL
    GOOGLE_CLOUD_CLIENT_X509_CERT_URL: VAR_GOOGLE_CLOUD_CLIENT_X509_CERT_URL

vpc_access_connector:
    name: projects/VAR_PROJECT_ID/locations/VAR_REGION/connectors/VAR_VPC_CONNECTOR
    egress_setting: all-traffic
