version: '3.8'

services:
  candidates-ms:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://docker:docker@db:5432/candidates
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=candidates
    volumes:
      - candidates_data:/var/lib/postgresql/data

volumes:
  candidates_data:
